using System;
namespace Problem2
{
    /*
        Even Fibonacci numbers
        Each new term in the Fibonacci sequence is generated by adding the previous two 
        terms. By starting with 1 and 2, the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        By considering the terms in the Fibonacci sequence whose values do not exceed four 
        million, find the sum of the even-valued terms.
    */
    class Program
    {
        static int Fibonacci(int f)
        {
            Console.WriteLine(f);
            if (f <= 1)
                return 1;
            return Fibonacci(f - 1) + Fibonacci(f - 2);
        }
        static int EvenFSum()
        {
            int sum = 0;
            return sum;
        }
        static void Main(string[] args)
        {
            Console.WriteLine(Fibonacci(10));
        }
    }
}
